export { default as BangDieuKhien } from './BangDieuKhien'
export { default as ChuyenNganh } from './ChuyenNganh'
export { default as DiemSinhVien } from './DiemSinhVien'
export { default as GiaoVien } from './GiaoVien'
export { default as Khoa } from './Khoa'
export { default as LopHoc } from './LopHoc'
export { default as MonHoc } from './MonHoc'
export { default as PhongDaoTao } from './PhongDaoTao'
export { default as TaiKhoan } from './TaiKhoan'
export { default as ThongTinSinhVien } from './ThongTinSinhVien'

